metadata:
  labels:
    {{- include "natsBox.labels" $ | nindent 4 }}
spec:
  containers:
  - {{ include "nats.loadMergePatch" (merge (dict "file" "nats-box/deployment/container.yaml" "ctx" $) .Values.natsBox.container) | nindent 4 }}

  # service discovery uses DNS; don't need service env vars
  enableServiceLinks: false

  volumes:
  # contexts secret
  - name: contexts
    secret:
      secretName: {{ .Values.natsBox.contextsSecret.name }}
