{{/*
Denne wrapper renderer kun et PodDisruptionBudget, når
Values.podDisruptionBudget.enabled er slaaet til.
*/}}
{{- include "nats.defaultValues" . }}
{{- with .Values.podDisruptionBudget }}
{{- if .enabled }}
{{- include "nats.loadMergePatch" (merge (dict "file" "pod-disruption-budget.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
