{{- with .Values.config.jetstream.fileStore }}
# Mappe hvor JetStream gemmer persistente data på disken.
store_dir: {{ .dir }}
# Brug PVC-størrelsen som øvre grænse for diskforbrug i det nuværende setup.
max_file_store: << {{ .pvc.size }} >>
{{- end }}
