{{- include "nats.defaultValues" . }}
{{- with .Values.natsBox }}
{{- if .enabled }}
# Denne template wrapper renderer secret til NATS Box contexts.
# Formålet er at oprette den secret som NATS Box kan laese sine forbindelsescontexts fra.
# Den egentlige resource bliver bygget i filen under files nats-box contexts-secret.
{{- with .contextsSecret}}
{{- include "nats.loadMergePatch" (merge (dict "file" "nats-box/contexts-secret/contexts-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
{{- end }}
